version: 2.1

jobs:
  hello-world:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Say Hello
          command: |
            echo "Hello World"

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Install
          command: |
            cd backend
            npm install
      - run:
          name: build
          command: |
            cd backend
            npm run build


workflows:
  default:
    jobs:
      - build-backend
