version: 2.1

jobs:
  hello-world:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Say Hello
          command: |
            echo "Hello World"

  lint-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Install
          command: |
            cd backend
            npm install
      - run:
          name: Lint
          command: |
            cd backend
            npm run build

  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Install
          command: |
            cd backend
            npm install
      - run:
          name: Lint
          command: |
            cd backend
            npm run test

  lint-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Install
          command: |
            cd frontend
            npm install
      - run:
          name: Lint
          command: |
            cd frontend
            npm run build


workflows:
  build:
    jobs:
      - lint-backend
      - test-backend:
          requires:
            - lint-backend

      - lint-frontend
